### ISSUE TITLE
Unable to run minimal example in webassembly

### ISSUE THREAD

**Issue by kajmaj87** [ArthurSonzogni/FTXUI#369]
I'm struggling to build the project correctly for webassembly. I've taken the slider example and created a minimal project with both a web assembly build and normal build. After running the project in browser I get the following error:

```
Uncaught (in promise) RuntimeError: Aborted(native code called abort())
    abort http://localhost:8888/build_webasm/ftxui_minimal.js:1466
    _abort http://localhost:8888/build_webasm/ftxui_minimal.js:4239
    createExportWrapper http://localhost:8888/build_webasm/ftxui_minimal.js:1510
    callMain http://localhost:8888/build_webasm/ftxui_minimal.js:5269
    doRun http://localhost:8888/build_webasm/ftxui_minimal.js:5326
    run http://localhost:8888/build_webasm/ftxui_minimal.js:5341
    runCaller http://localhost:8888/build_webasm/ftxui_minimal.js:5247
    removeRunDependency http://localhost:8888/build_webasm/ftxui_minimal.js:1432
    receiveInstance http://localhost:8888/build_webasm/ftxui_minimal.js:1599
    receiveInstantiationResult http://localhost:8888/build_webasm/ftxui_minimal.js:1617
    promise callback*createWasm/instantiateAsync/< http://localhost:8888/build_webasm/ftxui_minimal.js:1651
    promise callback*instantiateAsync http://localhost:8888/build_webasm/ftxui_minimal.js:1643
    createWasm http://localhost:8888/build_webasm/ftxui_minimal.js:1680
    <anonymous> http://localhost:8888/build_webasm/ftxui_minimal.js:4939
```

Is this a known issue? How could I debug this further? I'm building this with CMake and Emscripten.
What is not understandable for me is that, using the same approach, I can build your examples locally and they all work perfectly fine, there must be something missing in my implementation but I'm clueless.

I've created a repo with a Dockerfile and running commands for easy reproducibility. The example is based on index.html from your examples folder and I've taken the smallest example there was (slider).

Repo is here: 
https://github.com/kajmaj87/ftxui_minimal

**Comment by ArthurSonzogni** [comment]
Hello thanks for building the example!

I agree this was not easy to find. It too me ~18min to get the idea:

If you build in Debug mode you will see:
```
Uncaught (in promise) RuntimeError: Aborted(native code called abort())
    at abort (:8888/build/ftxui_minimal.js:1505:11)
    at _abort (:8888/build/ftxui_minimal.js:4307:7)
    at std::__2::__throw_system_error(int, char const*) (:8888/build/ftxui_minimal.wasm)
    at std::__2::thread::thread<void (*)(std::__2::atomic<bool>*, std::__2::unique_ptr<ftxui::SenderImpl<ftxui::Event>, std::__2::default_delete<ftxui::SenderImpl<ftxui::Event> > >), std::__2::atomic<bool>*, std::__2::unique_ptr<ftxui::SenderImpl<ftxui::Event>, std::__2::default_delete<ftxui::SenderImpl<ftxui::Event> > >, void>(void (*&&)(std::__2::atomic<bool>*, std::__2::unique_ptr<ftxui::SenderImpl<ftxui::Event>, std::__2::default_delete<ftxui::SenderImpl<ftxui::Event> > >), std::__2::atomic<bool>*&&, std::__2::unique_ptr<ftxui::SenderImpl<ftxui::Event>, std::__2::default_delete<ftxui::SenderImpl<ftxui::Event> > >&&) (:8888/build/ftxui_minimal.wasm)
    at ftxui::ScreenInteractive::Install() (:8888/build/ftxui_minimal.wasm)
    at ftxui::ScreenInteractive::Loop(std::__2::shared_ptr<ftxui::ComponentBase>) (:8888/build/ftxui_minimal.wasm)
    at main (:8888/build/ftxui_minimal.wasm)
    at :8888/build/ftxui_minimal.js:1549:22
    at callMain (:8888/build/ftxui_minimal.js:5365:15)
    at doRun (:8888/build/ftxui_minimal.js:5422:23)
```

So it fails when creating a thread.
The missing instructions from FTXUI you are missing are:
https://github.com/ArthurSonzogni/FTXUI/blob/aebde943523bb75da79ba45eb5b2e88d39a620e1/cmake/ftxui_set_options.cmake#L62-L67

**Comment by kajmaj87** [comment]
It works, thank you so much for your fast reply!
I'm still very new to webasm, c++ and cmake, can you please tell me how did you run the build in debug mode this way?

**Comment by ArthurSonzogni** [comment]
See this article:
https://riptutorial.com/cmake/example/7357/switching-between-build-types--e-g--debug-and-release

I modified the "CMAKE_BUILD_TYPE" from the CMakeCache file.

**Comment by kajmaj87** [comment]
Thanks!
