### ISSUE TITLE
When moving the mouse inside the application, a sequence of control characters of the terminal appears.

### ISSUE THREAD

**Issue by DanuulKa03** [ArthurSonzogni/FTXUI#844]
Before:
![Screenshot from 2024-04-18 19-30-21](https://github.com/ArthurSonzogni/FTXUI/assets/80038887/1fa81fa7-d0f8-417f-857f-02c206d3ee88)

After:
![Screenshot from 2024-04-18 19-30-55](https://github.com/ArthurSonzogni/FTXUI/assets/80038887/61689a7b-574a-4635-bcd3-e3500bd82667)

Why am I encountering such a phenomenon, what could I be doing wrong?
I will note some strange phenomena. At the same time, components and elements in the application do not work at all.

**Comment by ArthurSonzogni** [comment]
Hello!
This sounds unexpected. Could you please provide the following information:
- OS (I guess Windows on the screenshot?)
- Terminal emulator.
- Minimal example reproducing the bug.

**Comment by ArthurSonzogni** [comment]
Hello, would you have any updates?

**Comment by DanuulKa03** [comment]
Hello to you. It was difficult for me to repeat that action again; I was searching for ways to resolve it. In my application, a data stream is being read, and apparently, my stream was interpreting mouse data as part of the stream and displaying it on the screen. I fixed this by using another thread for reading. Thank you for trying to help.

**Comment by DanuulKa03** [comment]
The operating system was Ubuntu.
IDA Clion

**Comment by DanuulKa03** [comment]
But in reality, that was nothing compared to what I'm dealing with now.) After some time, I'm experiencing a memory leak, and the application crashes.)

**Comment by DanuulKa03** [comment]
If you're interested, here is the output from GDB related to my other issue:
```Thread 3 "log_monitor" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6ffe640 (LWP 7024)]
0x000055555562292f in ftxui::VerticalContainer::Render (this=0x555555772a30) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/container.cpp:106
106	      elements.push_back(it->Render());
#0  0x000055555562292f in ftxui::VerticalContainer::Render (this=0x555555772a30) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/container.cpp:106
#1  0x00005555555bfeb2 in operator() (__closure=0x5555557738b8) at /home/dika/CLionProjects/firmware-logger/Model/MainWindow/src/MainWindow.cpp:63
#2  0x00005555555c27b7 in std::__invoke_impl<std::shared_ptr<ftxui::Node>, MainWindow::UIBuilder()::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#3  0x00005555555c1f74 in std::__invoke_r<std::shared_ptr<ftxui::Node>, MainWindow::UIBuilder()::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/11/bits/invoke.h:116
#4  0x00005555555c1743 in std::_Function_handler<std::shared_ptr<ftxui::Node>(), MainWindow::UIBuilder()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/11/bits/std_function.h:291
#5  0x000055555563935c in std::function<std::shared_ptr<ftxui::Node> ()>::operator()() const (this=0x5555557738b8) at /usr/include/c++/11/bits/std_function.h:590
#6  0x000055555563ee98 in Impl::Render (this=0x555555773890) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/renderer.cpp:36
#7  0x00005555556236ee in ftxui::TabContainer::Render (this=0x55555576e380) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/container.cpp:224
#8  0x0000555555642adc in ftxui::(anonymous namespace)::ResizableSplitBase::RenderLeft (this=0x555555773c70) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/resizable_split.cpp:118
#9  0x000055555564285c in ftxui::(anonymous namespace)::ResizableSplitBase::Render (this=0x555555773c70) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/resizable_split.cpp:101
#10 0x00005555555c01d7 in operator() (__closure=0x555555773e68) at /home/dika/CLionProjects/firmware-logger/Model/MainWindow/src/MainWindow.cpp:82
#11 0x00005555555c2891 in std::__invoke_impl<std::shared_ptr<ftxui::Node>, MainWindow::UIBuilder()::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#12 0x00005555555c20fb in std::__invoke_r<std::shared_ptr<ftxui::Node>, MainWindow::UIBuilder()::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/11/bits/invoke.h:116
#13 0x00005555555c186b in std::_Function_handler<std::shared_ptr<ftxui::Node>(), MainWindow::UIBuilder()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/11/bits/std_function.h:291
#14 0x000055555563935c in std::function<std::shared_ptr<ftxui::Node> ()>::operator()() const (this=0x555555773e68) at /usr/include/c++/11/bits/std_function.h:590
#15 0x000055555563ee98 in Impl::Render (this=0x555555773e40) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/renderer.cpp:36
#16 0x000055555563d42a in Impl::Render (this=0x555555773ee0) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/modal.cpp:31
#17 0x000055555564905d in ftxui::ScreenInteractive::Draw (this=0x7fffffffd828, component=
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<ftxui::Modal(std::shared_ptr<ftxui::ComponentBase>, std::shared_ptr<ftxui::ComponentBase>, bool const*)::Impl, std::allocator<ftxui::Modal(std::shared_ptr<ftxui::ComponentBase>, std::shared_ptr<ftxui::ComponentBase>, bool const*)::Impl>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<ftxui::Modal(std::shared_ptr<ftxui::ComponentBase>, std::shared_ptr<ftxui::ComponentBase>, bool const*)::Impl, std::allocator<ftxui::Modal(std::shared_ptr<ftxui::ComponentBase>, std::shared_ptr<ftxui::ComponentBase>, bool const*)::Impl>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<ftxui::ComponentBase> (use count 4, weak count 0) = {...}) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/screen_interactive.cpp:778
#18 0x0000555555648d82 in ftxui::ScreenInteractive::RunOnce (this=0x7fffffffd828, component=std::shared_ptr<ftxui::ComponentBase> (empty) = {...}) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/screen_interactive.cpp:711
#19 0x0000555555648c41 in ftxui::ScreenInteractive::RunOnceBlocking (this=0x7fffffffd828, component=
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<ftxui::Modal(std::shared_ptr<ftxui::ComponentBase>, std::shared_ptr<ftxui::ComponentBase>, bool const*)::Impl, std::allocator<ftxui::Modal(std::shared_ptr<ftxui::ComponentBase>, std::shared_ptr<ftxui::ComponentBase>, bool const*)::Impl>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<ftxui::Modal(std::shared_ptr<ftxui::ComponentBase>, std::shared_ptr<ftxui::ComponentBase>, bool const*)::Impl, std::allocator<ftxui::Modal(std::shared_ptr<ftxui::ComponentBase>, std::shared_ptr<ftxui::ComponentBase>, bool const*)::Impl>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<ftxui::ComponentBase> (use count 4, weak count 0) = {...}) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/screen_interactive.cpp:701
#20 0x000055555565e55f in ftxui::Loop::RunOnceBlocking (this=0x7ffff6ffdcd0) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/loop.cpp:46
#21 0x000055555565e5c4 in ftxui::Loop::Run (this=0x7ffff6ffdcd0) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/loop.cpp:53
#22 0x00005555556476a7 in ftxui::ScreenInteractive::Loop (this=0x7fffffffd828, component=std::shared_ptr<ftxui::ComponentBase> (empty) = {...}) at /home/dika/CLionProjects/firmware-logger/cmake-build-debug/_deps/ftxui-src/src/ftxui/component/screen_interactive.cpp:493
#23 0x00005555555c0f1f in MainWindow::Run (this=0x7fffffffd740) at /home/dika/CLionProjects/firmware-logger/Model/MainWindow/src/MainWindow.cpp:90
#24 0x000055555556a3c6 in operator() (__closure=0x555555773e98) at /home/dika/CLionProjects/firmware-logger/main.cpp:50
#25 0x000055555556c352 in std::__invoke_impl<void, run(sigslot::signal<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>&, MainWindow&)::<lambda()> >(std::__invoke_other, struct {...} &&) (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#26 0x000055555556c2a8 in std::__invoke<run(sigslot::signal<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>&, MainWindow&)::<lambda()> >(struct {...} &&) (__fn=...) at /usr/include/c++/11/bits/invoke.h:96
#27 0x000055555556c1ec in std::thread::_Invoker<std::tuple<run(sigslot::signal<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>&, MainWindow&)::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x555555773e98) at /usr/include/c++/11/bits/std_thread.h:259
#28 0x000055555556c11a in std::thread::_Invoker<std::tuple<run(sigslot::signal<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>&, MainWindow&)::<lambda()> > >::operator()(void) (this=0x555555773e98) at /usr/include/c++/11/bits/std_thread.h:266
#29 0x000055555556c00e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<run(sigslot::signal<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>&, MainWindow&)::<lambda()> > > >::_M_run(void) (this=0x555555773e90) at /usr/include/c++/11/bits/std_thread.h:211
#30 0x00007ffff7cdc253 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#31 0x00007ffff7894ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#32 0x00007ffff7926850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
Quit
```


`MainWindow.cpp`
```
#include <string>



#include "MainWindow.h"

using namespace ftxui;

std::function<void()> handleMenuClick(MainWindow &win)
// возможно создание такой функции ошибка
{
    return [&]
    {
        win.key = win.itemsTab[win.selected_tab].keyFilter; // нужно чтобы обновлялась строка input при переходе на новую закладку

    };
}

MainWindow::MainWindow(size_t countTabulations_)
    : title_("Monitor log"), countTabulations(countTabulations_)
{
    for (size_t i = 0; i < countTabulations; i++) {
        tab_titles.push_back("Tab " + std::to_string(i + 1));
        itemsTab.emplace_back();
    }

    input_key = Input(&key, "key entry field"/*, {.on_change = filterOwner()}*/);
}

void MainWindow::UIBuilder()
{

    // Instance the main and modal components:
    bool modal_shown = false; //отображается ли окно или нет
    std::string filePath; //путь до файла, который передается через диалоговое окно
    modal_component = DialogComponent(filePath, exportFile(), hideModal(modal_shown));

    buttonExport = Button("Export", showModal(modal_shown));

    containerButton = Container::Vertical({
                                                   input_key,
                                                   buttonExport,
                                               });
    leftContainer = Renderer(containerButton, [&]
    {
        return vbox({

                        hbox({
                                 text("key : "),
                                 input_key->Render()
                             }),

                        separator(),
                        buttonExport->Render(),
                    });
    });

    //добавление в tab обьектов, для отображения
    tab = Container::Tab( {},&selected_tab );
    for (size_t i = 0; i < countTabulations; i++)
        tab->Add(Renderer(itemsTab[i].containerLog, [this, i] {
            return hbox({itemsTab[i].containerLog->Render() | vscroll_indicator | yframe | xflex});
        }));


    tab_toggle = HMenu(&tab_titles, &selected_tab, *this);

    layout = ResizableSplitLeft(leftContainer, tab, &size);

    containerMain = Container::Vertical({
                                                 tab_toggle,
                                                 layout,
                                             });

    mainWindow = Renderer(containerMain, [&]
    {
        return vbox({
                        tab_toggle->Render(),
                        separator(),
                        layout->Render() | flex,
                    }) | border;
    });

    mainWindow |= Modal(modal_component, &modal_shown);
//    screen.Loop(mainWindow);
}

void MainWindow::Run() {
    screen.Loop(mainWindow);
}

// Это обработчик событий сохранения файла
std::function<void()> MainWindow::exportFile()
{
    return [&]
    {

    };
}
std::function<void()> MainWindow::showModal(bool &modal_shown)
{
    return [&]
    {
        modal_shown = true;
    };
}
std::function<void()> MainWindow::hideModal(bool &modal_shown)
{
    return [&]
    {
        modal_shown = false;
    };
}
```

`MainWindow.h`

```
#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <iostream>
#include <string>
#include <vector>
#include <type_traits>

#include "../../TabController/include/TabController.hpp"
#include "../../DialogComponent/include/DialogComponent.hpp"
#include "../../HMenu/include/HMenu.hpp"

#include "ftxui/component/component.hpp"  // for Renderer, ResizableSplitBottom, ResizableSplitLeft, ResizableSplitRight, ResizableSplitTop
#include "ftxui/component/screen_interactive.hpp"  // for ScreenInteractive
#include "ftxui/dom/elements.hpp"  // for Element, operator|, text, center, border

class MainWindow
{
public:
    explicit MainWindow(size_t countTabulations_);
    void UIBuilder();
    void Run();

    std::vector<TabController> &getTabController() {return itemsTab;}
    ScreenInteractive &getScreen() {return screen;}
private:
    const size_t countTabulations;

    std::string title_;

    std::string key;

    Component input_key, mainWindow, tab_toggle, layout, buttonExport, tab, containerButton, modal_component, leftContainer, containerMain;
    ScreenInteractive screen = ScreenInteractive::Fullscreen(); //хз как сделать по другому, у него нету коструктора
    // по умолчанию
    int size = 30; //размер окна по умолчанию, который может меня окно

    int selected_tab = 0;
    std::vector<std::string> tab_titles; //хранит название вкладок

    std::vector<TabController> itemsTab; //окна вкладок

    static std::function<void()> showModal(bool &modal_shown); //вкл. окна

    static std::function<void()> hideModal(bool &modal_shown); //выкл. окна

    static std::function<void()> exportFile(); //экспорт файла

    friend std::function<void()> handleMenuClick(MainWindow &win); // клик по кнопке меню
};

#endif
```

**Comment by ArthurSonzogni** [comment]
Hello,
There are a couple of files missing, so that I can't attempt reproducing this.
